### ISSUE TITLE
引用文献的问题

### ISSUE THREAD

**Issue by shincfk** [h2y/xsyu-latex#1]
用\cite{}引用文献，在.tex中应用编译后显示？，具体\cite{}应该在哪个文件中引用可以引用文献，还有个疑惑，thesis.bbl中为何放个参考文献，使用中想了一会儿才意识到pdf中的参考文献藏在这里。

**Comment by h2y** [comment]
参考文献从百度学术或google 学术搜索找到后，导出参考文献bibtex，将bibtex内容粘贴到XXX.bib文件中，然后通过\cite｛Nnnnn｝进行索引其中Nnnnn是导出的bibtex的id，编译的时候先用bibliography （或bibtex），再使用xelatex编译。

thesis.bbl文件是bibliography 命令编译后生成的中间文件，不可以对其修改。

bib文件在目录中仔细找。

**Comment by shincfk** [comment]
嗯，对的，当时意识到后很快解决了，不过你回复了，还是谢谢了
